### ISSUE TITLE
Add ability to toggle certain warnings off

### ISSUE THREAD

**Issue by mateenkasim** [authzed/spicedb-vscode#12]
First of all, thanks for making this extension and LSP! The coloring, hovers, and lint are awesome to have during schema development. 🎉 

Onto the issue: My schema has something similar to this:
```
definition folder {
    relation editor: user
    permission create_child_folder = editor
    // ... etc
}
```

This produces this warning:
`Permission "create_child_folder" references parent type "folder" in its name; it is recommended to drop the suffix`

I understand what this warning is getting at, but it's not exactly relevant in this case – the "child_folder" just happens to be the same resource as the parent "folder", hence the suffix. Since other warnings are still valuable, it would be great to selectively turn off this warning. 

Generally, I'd like to toggle on/off whatever warnings are best for me. Perhaps a `// zed-disable-warning: parent-name-in-suffix` at the top of the file, or something in the `.vscode/settings` file?

**Comment by josephschorr** [comment]
@mateenkasim Mind filing this against SpiceDB itself? All the diagnostics are generated by this package: https://github.com/authzed/spicedb/blob/main/pkg/development/warningdefs.go

**Comment by josephschorr** [comment]
Should be easy to add something that uses the comment metadata on the nodes and disables it

**Comment by mateenkasim** [comment]
Happy to!
